name: Database update

on:
  push:
    branches:
      - main

jobs:
  update_database:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update database
        run: |
          ls
          LIST=`git diff --name-only -r ${{ github.event.before }} ${{ github.event.after }} **/*.json`

          for FILE in $LIST
          do
              docker run --env-file ./.env -v ./database.db:/database.db -v "$FILE":/bom.json fnxpt/cyclonedx-enrich:latest --database-import bom.json
          done
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Inserted new boms into database
          commit_options: '--no-verify --signoff'
          file_pattern: 'database.db'