name: Database update

on:
  push:
    branches:
      - main

jobs:
  update_database:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update database
        run: |
          LIST=`git diff --name-only -r ${{ github.event.before }} ${{ github.event.after }} **/*.json`

          for FILE in $LIST
          do
              docker run --env-file ./.env fnxpt/cyclonedx-enrich:latest --database-import "$FILE"
          done
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Inserted new boms into database
          commit_options: '--no-verify --signoff'
          file_pattern: 'database.db'